// src/constants/hotelData.js
export const hotels = [
  {
    id: 1,
    name: "Grand Plaza Hotel",
    location: "Mumbai, Maharashtra",
    rating: 4.5,
    price: 3500,
    originalPrice: 4200,
    image: "/placeholder.svg?height=200&width=300",
    roomType: "Deluxe",
    amenities: ["WiFi", "AC", "Pool", "Gym"],
    discount: 17,
    reviews: 1250,
  },
  {
    id: 2,
    name: "Ocean View Resort",
    location: "Goa, India",
    rating: 4.8,
    price: 5200,
    originalPrice: 6000,
    image: "/placeholder.svg?height=200&width=300",
    roomType: "Suite",
    amenities: ["WiFi", "AC", "Pool", "Restaurant"],
    discount: 13,
    reviews: 890,
  },
  {
    id: 3,
    name: "Mountain Retreat",
    location: "Shimla, Himachal Pradesh",
    rating: 4.2,
    price: 2800,
    originalPrice: 3200,
    image: "/placeholder.svg?height=200&width=300",
    roomType: "Standard",
    amenities: ["WiFi", "AC", "Gym", "Parking"],
    discount: 12,
    reviews: 450,
  },
  {
    id: 4,
    name: "City Center Inn",
    location: "Bengaluru, Karnataka",
    rating: 4.0,
    price: 2200,
    originalPrice: 2500,
    image: "/placeholder.svg?height=200&width=300",
    roomType: "Economy",
    amenities: ["WiFi", "Parking"],
    discount: 12,
    reviews: 300,
  },
  {
    id: 5,
    name: "Heritage Palace",
    location: "Jaipur, Rajasthan",
    rating: 4.7,
    price: 4800,
    originalPrice: 5500,
    image: "/placeholder.svg?height=200&width=300",
    roomType: "Luxury",
    amenities: ["WiFi", "AC", "Pool", "Restaurant", "Pet-friendly"],
    discount: 13,
    reviews: 670,
  },
  {
    id: 6,
    name: "Desert Oasis Hotel",
    location: "Jaisalmer, Rajasthan",
    rating: 4.3,
    price: 3000,
    originalPrice: 3600,
    image: "/placeholder.svg?height=200&width=300",
    roomType: "Deluxe",
    amenities: ["WiFi", "AC", "Gym"],
    discount: 17,
    reviews: 520,
  },
  {
    id: 7,
    name: "Coastal Breeze Hotel",
    location: "Kochi, Kerala",
    rating: 4.6,
    price: 4000,
    originalPrice: 4500,
    image: "/placeholder.svg?height=200&width=300",
    roomType: "Suite",
    amenities: ["WiFi", "AC", "Pool", "Restaurant"],
    discount: 11,
    reviews: 800,
  },
  {
    id: 8,
    name: "Urban Escape Hotel",
    location: "Delhi, India",
    rating: 4.1,
    price: 2700,
    originalPrice: 3000,
    image: "/placeholder.svg?height=200&width=300",
    roomType: "Standard",
    amenities: ["WiFi", "AC", "Gym", "Parking"],
    discount: 10,
    reviews: 600,
  },
];

export const amenityIcons = {
  WiFi: "Wifi",
  AC: "Snowflake",
  Pool: "Waves",
  Gym: "Dumbbell",
  Parking: "Car",
  Restaurant: "Utensils",
  "Pet-friendly": "PawPrint",
};
export const roomTypes = [
  { value: "Deluxe", label: "Deluxe" },
  { value: "Suite", label: "Suite" },
  { value: "Standard", label: "Standard" },
  { value: "Economy", label: "Economy" },
  { value: "Luxury", label: "Luxury" },
];
