"""Initial migration

Revision ID: 2d2226d7957b
Revises: 
Create Date: 2025-06-24 21:09:31.913532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d2226d7957b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('hotel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('check_in', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('check_out', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('guests', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotel.id'], name=op.f('booking_hotel_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('booking_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('booking_pkey'))
    )
    # ### end Alembic commands ###
